import "./globals.css";
import Image from "next/image";
import profilePic from "../../public/KenshinKyu_big_brain_nick_e39a2fe1-19b3-4c27-b06d-9581284e54bd.png";

export const metadata = {
  title: "Something weird",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const year = new Date().getFullYear();

  return (
    <html lang="en">
      <body>
        <div className="header">
          <div className="top">
            <div className="left">
              <h3>Logo not logo</h3>
            </div>
            <div className="right "></div>
          </div>
          <div className="bottom">
            <div className="left">
              <h1>
                Big brain Richard
                <br />
                That&apos;s what <span className="italic">they</span> say
              </h1>
              <p className="subtext">
                Welcome to my personal site. There isn&#39; t much here. Enjoy!
              </p>
              <button className="mt-5">Now includes flexbox</button>
            </div>
            <div className="right">
              <Image
                priority={true}
                src={profilePic}
                alt="This is actually Big Brain Nick, but you won't know that!"
                height={150}
                width={150}
              />
            </div>
          </div>
        </div>
        {children}
        <div className="quote">
          <blockquote>
            “I&apos;m not an abstractionist. I&apos;m not interested in the
            relationship of color or form or anything else. I&apos;m interested
            only in expressing basic human emotions: tragedy, ecstasy, doom, and
            so on.”
          </blockquote>
          <cite> - Mark Rothko (not me)</cite>
        </div>
        <div className="cta">
          <div className="callout">
            <div className="callout-text">
              <h3>Call to no action!</h3>
              <p>
                There is nothing to sign up to, so don&apos;t bother trying.
                Gump.
              </p>
            </div>
            <div className="callout-button">
              <a href="https://www.bbc.co.uk">
                <button>Go away</button>
              </a>
            </div>
          </div>
        </div>
        <div className="footer">
          <div className="copyright">
            <p>Copyright © Richard Washington {year}</p>
          </div>
        </div>
      </body>
    </html>
  );
}
